[CB-3795] Modified check_req to ensure NDK tools are on path + removed BBNDK checks
Reviewed by Jeffrey Heifetz <jheifetz@blackberry.com>
Tested by Tracy Li <tli@blackberry.com>

diff --git a/blackberry10/bin/check_reqs b/blackberry10/bin/check_reqs
--- a/blackberry10/bin/check_reqs
+++ b/blackberry10/bin/check_reqs
@@ -17,15 +17,32 @@
 #       under the License.
 #
 #!/bin/sh
-if command -v node >/dev/null 2>&1; then
-    if command -v npm >/dev/null 2>&1; then
-        node "$( dirname "$0" )/check_reqs.js" "$@"
-    else
-        echo "npm cannot be found on the path. Aborting."
-        exit 1
-    fi
-else
+
+NODE=$(command -v node)
+NPM=$(command -v npm)
+PACKAGER=$(command -v blackberry-nativepackager)
+DEPLOYER=$(command -v blackberry-deploy)
+SIGNER=$(command -v blackberry-signer)
+
+if [ -z "$NODE" ]; then
     echo "Node cannot be found on the path. Aborting."
-    exit 1
+    EXIT_CODE=1
+elif [ -z "$NPM" ]; then
+    echo "npm cannot be found on the path. Aborting."
+    EXIT_CODE=1
+elif [ -z "$PACKAGER" ]; then
+    echo "blackberry-nativepackager cannot be found on the path. Aborting."
+    EXIT_CODE=1
+elif [ -z "$DEPLOYER" ]; then
+    echo "blackberry-deploy cannot be found on the path. Aborting."
+    EXIT_CODE=1
+elif [ -z "$SIGNER" ]; then
+    echo "blackberry-signer cannot be found on the path. Aborting."
+    EXIT_CODE=1
+else
+    node "$( dirname "$0" )/check_reqs.js" "$@"
+    EXIT_CODE=0
 fi
+
+exit $EXIT_CODE
 
