[CB-3380] Updates scripts to work better with Node dependency - check_reqs now completes preliminary work in bash/batch ensuring   completion without node installed - create now calls npm install first
Revewied by Bryan Higgins <bhiggins@blackberry.com>

diff --git a/blackberry10/bin/create b/blackberry10/bin/create
--- a/blackberry10/bin/create
+++ b/blackberry10/bin/create
@@ -23,10 +23,17 @@
 #
 #!/bin/sh
 
-if ! [ -d ../node_modules ] ; then
-    echo "node dependencies not found. Executing 'sudo npm install'"
-    echo "this will require your system password"
-    sudo npm install
-fi
+CURRENT_DIR=$(pwd)
+BIN_DIR=$(dirname "$0")
 
-node $( dirname "$0" )"/create.js" "$@"
+#Run npm install every time (even if node_modules folder is present) to cover platform upgrade
+cd $BIN_DIR/..
+#Removed sudo usage so that node modules are not ownder by root
+npm install
+cd $CURRENT_DIR
+
+if [ $? -eq 0 ]; then
+  echo "NPM install failed. Aborting."
+else
+  node $BIN_DIR/create.js "$@"
+fi
